- title: Welcome
  subtitle: welcome indeed
  body: |
    welcome. welcome. welcome.

    really. you are welcome.

- body: let us login
  command:
    filename: cf
    args: [login]

- body: this is a ci only page
  ci: true
  command:
    filename: echo
    args: [this, command, only, runs, on, ci]

- body: let us deploy
  command:
    filename: cf
    args: [push]
