spring:
  data:
    rest:
      basePath: /api
      default-page-size: 10
      max-page-size: 100
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/message-service
    username: message-service
    password: password
  jpa:
    properties:
      hibernate:
        temp.use_jdbc_metadata_defaults: false
    database: postgresql

